---
title: "OU Data"
author: "venkat"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("OUData.csv")
```

```{r}
sum(is.na(data))
sum(data=="NULL")
data[data=="NULL"] <-NA
colSums(is.na(data))
```
```{r}
data <- na.omit(data)
```

```{r}
colSums(is.na(data))
```

```{r}
data$ObservationRecordKey <- NULL
data$InitPatientClassAndFirstPostOUClass <- NULL
```

```{r}
summary(data)
```
```{r}
data$Gender<-NULL
data$PrimaryInsuranceCategory<- NULL
data$DRG01<- NULL

```

```{r}
data$BloodPressureUpper<- as.numeric(data$BloodPressureUpper)
data$BloodPressureDiff<- as.numeric(data$BloodPressureDiff)
data$Pulse <- as.numeric(data$Pulse)
data$PulseOximetry <- as.numeric(data$PulseOximetry)
data$Respirations <- as.numeric(data$Respirations)
data$Temperature <- as.numeric(data$Temperature)

```
```{r}
data <- na.omit(data)
```

```{r}
str(data)
```
```{r}

```


```{r}

```


```{r}
# select the columns for clustering
#clust_data <- data[, c("Temperature", "Pulse", "BloodPressureUpper","BloodPressureLower")]


# scale the data
scaled_clust_data <- scale(data)

# k-means clustering
set.seed(123)
kmeans_clusters <- kmeans(scaled_clust_data, centers = 4)
```


```{r}
# view the cluster centers
data_lab=kmeans_clusters$centers
data_lab
```


```{r}
#kmeans_clusters$cluster
```

```{r}
labled_df <- cbind(data, cluster = kmeans_clusters$cluster)
```


```{r}
df_cent <- aggregate(. ~ cluster, data = labled_df, FUN = mean)
df_cent
```



```{r}
library(ggplot2)

ggplot(labled_df, aes(x = Temperature, y = Pulse, color = factor(cluster))) +
  geom_point() +
  xlab("Temperature") +
  ylab("Pulse") +
  ggtitle("Clustered OU Data") +
  theme_bw()
```


```{r}
ggplot() +
  geom_point(data = labled_df, aes(x = Temperature, y = Pulse, color = factor(cluster))) +
  geom_point(data = df_cent, aes(x = Temperature, y = Pulse), color = "blue", size = 5) +
  xlab("Temperature") +
  ylab("Pulse") +
  ggtitle("Clustered OU Data with Centers") +
  theme_bw()

```


```{r}
library(ggplot2)
wss <- numeric(20)

```

```{r}
for (k in 1:20) {
  
  model <- kmeans(scaled_clust_data, centers = k)
  
  wss[k] <- model$tot.withinss
}
```


```{r}
wss_df <- data.frame(k = 1:20, wss = wss)
```


```{r}
# Plot the WSS values against k using ggplot2
ggplot(wss_df, aes(x = k, y = wss)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters (k)") +
  theme_bw()
```
